repos:
  - repo: local
    hooks:
      - id: uv-format
        name: uv format
        entry: uv format
        language: system
        types: [python]
        pass_filenames: false
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.7
    hooks:
      - id: docformatter
        additional_dependencies: [tomli]
        args: [--in-place, --config, ./pyproject.toml]
